FROM nvcr.io/nvidia/vllm:26.06-py3@sha256:bebcf9576b1720214319ee5c7ee4f7661954cbbf59ed3fcd188cd79a67f1967e

RUN python3 -m pip install --no-cache-dir \
    "rank-llm[api] @ git+https://github.com/castorini/rank_llm.git@8ad18be76c90aa97ffae50b84dbc326bedc724fd"

ENTRYPOINT ["rank-llm"]
